#sudo: false
# travis-ci.org build & test configuration
language: python

matrix:
    include:
        - python: 2.7
        - python: 3.6
        - python: 3.7-dev
    allow_failures:
        - python: 3.7-dev

install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then curl --silent http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -o miniconda.sh; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi

  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --set show_channel_urls yes
  - conda create -q -n testenv python=${TRAVIS_PYTHON_VERSION%-*}
  - export CONDA_ENV_PATH=$HOME/miniconda/envs/testenv
  - source activate testenv
  - pip install -r requirements/test.txt

script:
  - pytest --cov

after_success:
  - coverage combine
  - codecov

cache: apt

deploy:
  provider: pypi
  user: tai.sakuma
  distributions: sdist bdist_wheel --universal
  password:
    secure: LX88ozwHcjOSZQf2LJQzKWt6IrcPmZn2C9d4Qm6uuY/rDwMNwQBdkNKQNdI4gJXY70lDgcej1H751eCACszjG/sMJ37C6BsZzql6/v66LYGwf0kBrMZhVVGGsSq3kORAdQbH2EZ9FrMoD6yg3IDL1sBe9eju/pqs3SrikzXjJ5xizErJoWyiRPBb2OT2fkZWmTRkwvo5vS86Z1Fu5lD97PjffgdTnXcWo0NPQ3E24rnb6nqC8CEv9adsVKclsrmu3hHb22MtEhRFOAy80W5Zev343XxPZFz0ODBdGPgYKFItng0uvCx8TBFAQ7Qi8q0R+5VDTm9WPLepxgeuRQNK/lolpilP98CmLIUreFvWwMLKeN7jbBK3UZBWPQm3DowSogmrMTJOl3wHnJwHSIiPbuJZUZj1yxzPnMYhRCRVYihEqhIdp/7XYBNsKEqUtgpgwKO0D+i1hai3nUc+6n8xWQvAUc0oT9epqEwKz2Dw3q5kKzzUG1yzaKQwxlkWXJdIvQe8J4O6IOceH4K3NMCW81MP2WsZG+1uOkGKJFqWBRp6GaE35vAr46nPKXC8AvDRKCOXCzQMVhCIWYq9dPRGFPw6mSKpsyZTnDgWf+NrDMveDQCi0Xqsu/Yb2TVdOIOYxo8E9myrOXu/cs1CpRfBrf7NsowqPYoGq0v4poAb678=
  on:
    tags: true
    python: 3.6
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
